create_clock -period 40.000 -name clk_12MHz -waveform {0.000 20.000} [get_ports clk]
set_property PACKAGE_PIN E18 [get_ports {Out[3]}]
set_property PACKAGE_PIN E13 [get_ports {Out[1]}]
set_property PACKAGE_PIN F13 [get_ports {Out[2]}]
set_property PACKAGE_PIN H15 [get_ports {Out[0]}]
set_property PACKAGE_PIN H14 [get_ports In]
set_property PACKAGE_PIN H18 [get_ports Rev]
set_property PACKAGE_PIN G18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {Out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Out[0]}]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports In]
set_property IOSTANDARD LVCMOS33 [get_ports Rev]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
